services:
  backend-1:
    image: gabxdevv/rinha-backend-2025-java-gabxdev-unix:1.0.0
    restart: always
    volumes:
      - /tmp:/tmp
    environment:
      RETRY_API_DEFAULT: 15
      WORKER_POOL_SIZE: 16
      URL_PROCESSOR_DEFAULT: http://payment-processor-default:8080/payments
      URL_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080/payments
      UDP_CHANNEL_INTERNAL_PORT: 9003
      EXTERNAL_UDP_HOST: backend-2
      EXTERNAL_UDP_PORT: 9004
      API_UDP_PORT: 9095
      API_MASTER: true
      LB_UDP_HOST: load-balancer
      HANDLER_UDP_POOL_SIZE: 6
      SOCKET_PATH: /tmp/api1.sock
      JAVA_OPTS: >-
        -server
        -XX:+UseG1GC
        -XX:+UseFastAccessorMethods
        -Xlog:disable
        -XX:-PrintGC
        -XX:+UseStringCache
        -XX:-PrintGCDetails
        -XX:-FlightRecorder
        -XX:+DisableExplicitGC
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '125MB'

  backend-2:
    image: gabxdevv/rinha-backend-2025-java-gabxdev-unix:1.0.0
    restart: always
    volumes:
      - /tmp:/tmp
    environment:
      RETRY_API_DEFAULT: 15
      WORKER_POOL_SIZE: 16
      URL_PROCESSOR_DEFAULT: http://payment-processor-default:8080/payments
      URL_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080/payments
      UDP_CHANNEL_INTERNAL_PORT: 9004
      EXTERNAL_UDP_HOST: backend-1
      EXTERNAL_UDP_PORT: 9003
      HANDLER_UDP_POOL_SIZE: 6
      SOCKET_PATH: /tmp/api2.sock
      JAVA_OPTS: >-
        -server
        -XX:+UseG1GC
        -XX:+UseFastAccessorMethods
        -Xlog:disable
        -XX:-PrintGC
        -XX:+UseStringCache
        -XX:-PrintGCDetails
        -XX:-FlightRecorder
        -XX:+DisableExplicitGC
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '125MB'

  load-balancer:
    image: gabxdevv/loud-balance-java-gabxv-unix:1.0.0
    restart: always
    volumes:
      - /tmp:/tmp
    depends_on:
      - backend-1
      - backend-2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "100MB"
    environment:
      BACK_END_1_URL: backend-1
      BACK_END_2_PORT: 9095
      JAVA_OPTS: >-
        -server
        -XX:+UseG1GC
        -XX:+UseFastAccessorMethods
        -Xlog:disable
        -XX:-PrintGC
        -XX:+UseStringCache
        -XX:-PrintGCDetails
        -XX:-FlightRecorder
        -XX:+DisableExplicitGC

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

#volumes:
#  tmp-sockets:
#    driver: local
#    driver_opts:
#      type: tmpfs
#      device: tmpfs