services:
  backend1:
    image: ronssm/copirinhago:latest
    environment:
      - POSTGRES_CONN=postgres://user:password@db:5432/copirinha?sslmode=disable
      - LOG_LEVEL=DEBUG
    networks:
      - backend
      - payment-processor
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9999/payments-summary"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "110MB"
  backend2:
    image: ronssm/copirinhago:latest
    environment:
      - POSTGRES_CONN=postgres://user:password@db:5432/copirinha?sslmode=disable
      - LOG_LEVEL=DEBUG
    networks:
      - backend
      - payment-processor
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9999/payments-summary"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "110MB"
  nginx:
    image: nginx:latest
    depends_on:
      - backend1
      - backend2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    networks:
      - backend
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "20MB"
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=copirinha
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - LOG_LEVEL=DEBUG
    volumes:
      - ./sql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./sql/dml.sql:/docker-entrypoint-initdb.d/dml.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d copirinha"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "110MB"
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
