services:
  rinhadebackend-aot:
    &api
    hostname: api01
    image: vyctor17/rinhadebackendaot:2025
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    healthcheck:
      test: curl --silent --fail http://localhost:8080/payments-summary || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    environment:
      - ConnectionStrings__Redis=redis:6379
      - DB_HOSTNAME=Host=db;Database=rinha;Username=admin;Password=123;No Reset On Close=true;Max Auto Prepare=10;Auto Prepare Min Usages=1;Pooling=true;Maximum Pool Size=100
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "60MB"

  rinhadebackend-aot02:
    <<: *api 
    hostname: api02

  rinhadebackend-aot.worker:
    image: vyctor17/rinhadebackendaotworker:2025
    networks:
      - backend
      - payment-processor
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - ConnectionStrings__Redis=redis:6379
      - Gateways__Primary=http://payment-processor-default:8080
      - Gateways__Fallback=http://payment-processor-fallback:8080
      - DB_HOSTNAME=Host=db;Database=rinha;Username=admin;Password=123;No Reset On Close=true;Max Auto Prepare=10;Auto Prepare Min Usages=1;Pooling=true;Maximum Pool Size=100
      - Workers__ConcurrencyLevel=1
      - Workers__BatchSize=200
      - Workers__FlushTimeoutMs=20
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "90MB"

  nginx:
    image: nginx:latest
    networks:
      - backend
      - payment-processor
    volumes:
     - ./nginx-conf/default.conf:/etc/nginx/nginx.conf
    depends_on:
      rinhadebackend-aot:
        condition: service_healthy
      rinhadebackend-aot02:
        condition: service_healthy
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "15MB"

  db:
    image: postgres:17-alpine
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./pg-conf/script.sql:/docker-entrypoint-initdb.d/script.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0 -c log_disconnections=0 -c log_connections=0 -c log_duration=0 -c log_statement=none -c logging_collector=off -c effective_io_concurrency=200 -c random_page_cost=1.1 -c checkpoint_completion_target=0.9
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d rinha"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "120MB"


  redis:
    image: redis:7.2-alpine
    container_name: redis-cache
    hostname: redis
    volumes:
      - ./redis-conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 3s
    ports:
      - "6379:6379"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

