services:
  nginx:
    image: nginx:latest
    container_name: nginx-lb
    hostname: nginx-lb
    ports:
      - 9999:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - memsock:/tmp
    networks:
      - backend
      - payment-processor
    depends_on:
      - backend-1
      - backend-2
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '210M'
    restart: unless-stopped

  backend-1: &backend-template
    image: rodrigomilitao/rinha-go-in-memory:2025-v1
    ports:
      - "6061:6060"
    expose:
      - '8080'
    networks:
      - backend
      - payment-processor
    volumes:
      - memsock:/tmp
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - SOCKET_PATH=/tmp/api1.sock
      - OTHER_SOCKET_PATH=/tmp/api2.sock
      - SUMMARY_URL=http://app2:8080/internal/payments-summary
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '70MB'
    restart: unless-stopped

  backend-2:
    ports:
      - "6062:6060"
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - SOCKET_PATH=/tmp/api2.sock
      - OTHER_SOCKET_PATH=/tmp/api1.sock  
      - SUMMARY_URL=http://app1:8080/internal/payments-summary
    <<: *backend-template

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  memsock:
