services:
  load-balance-one:
    image: alexroza/ld-tr
    environment:
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "167MB"
    networks:
      - backend
      - payment-processor

  load-balance-two:
    image: alexroza/ld-tr
    environment:
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "167MB"
    networks:
      - backend
      - payment-processor

  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - load-balance-one
      - load-balance-two
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "15MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
