x-service-templates:
  api: &api
    image: gabrieleiro/rinha-de-backend-2025-api:4.0
    networks:
      - rinha-de-backend-2025
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"
    depends_on:
      - tracker

services:
  api-1: 
    <<: *api
    hostname: api-1
    ports:
      - "8888:80"
    environment:
      DEFAULT_PROCESSOR_URL: "http://payment-processor-default:8080"
      FALLBACK_PROCESSOR_URL: "http://payment-processor-fallback:8080"
      TRACKER_URL: "tracker:1111"
      PORT: "80"
      ADDRESS: ":8888"

  api-2:
    <<: *api
    hostname: api-2
    ports:
      - "7777:80"
    environment:
      DEFAULT_PROCESSOR_URL: "http://payment-processor-default:8080"
      FALLBACK_PROCESSOR_URL: "http://payment-processor-fallback:8080"
      TRACKER_URL: "tracker:1111"
      PORT: "80"
      ADDRESS: ":7777"

  load-balancer:
    image: gabrieleiro/rinha-de-backend-2025-load-balancer:4.0
    networks:
      - rinha-de-backend-2025
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "50MB"
    ports:
      - "9999:9999"
    environment:
      ADDRESS: ":9999"
      SERVERS: "api-1:8888,api-2:7777"
    depends_on:
      - api-1
      - api-2

  tracker:
    hostname: tracker
    image: gabrieleiro/rinha-de-backend-2025-tracker:4.0
    networks:
      - rinha-de-backend-2025
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"
    expose:
      - "1111/udp"
    ports:
      - "1111:1111/udp"
    environment:
      ADDRESS: ":1111"

networks:
  rinha-de-backend-2025:
    name: rinha-de-backend-2025
    driver: bridge
  payment-processor:
    external: true
