services:
  #LB
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"

  #app
  api01: &api
    hostname: api01
    container_name: payments-01
    image: ghcr.io/andrelucasti/rinha-backend-2025-payments:latest
    environment:
      PAYMENT_PROCESSOR_DEFAULT_BASE_URL: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_FALLBACK_BASE_URL: http://payment-processor-fallback:8080
      REDIS_URL: redis://redis:6379
      REDIS_MAX_POOL_SIZE: 50
      REDIS_MAX_POOL_WAITING: 1000
      PORT: 8080
      CONSUMER_NAME: payments-01
      CONSUMER_BLOCK: 5000
      CONSUMER_COUNT: 3
      CONSUMER_DELAY: 1
    networks:
      - rinha-network
      - payment-processor
    restart: unless-stopped
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "120MB"

  api02:
    # Essa sintaxe reusa o que foi declarado em 'api01'.
    <<: *api
    hostname: api02
    container_name: payments-02
    environment:
      PAYMENT_PROCESSOR_DEFAULT_BASE_URL: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_FALLBACK_BASE_URL: http://payment-processor-fallback:8080
      REDIS_URL: redis://redis:6379
      REDIS_MAX_POOL_SIZE: 50
      REDIS_MAX_POOL_WAITING: 1000
      PORT: 8080
      CONSUMER_NAME: payments-02
      CONSUMER_BLOCK: 5000
      CONSUMER_COUNT: 3
      CONSUMER_DELAY: 1
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "120MB"

  #redis
  redis:
    image: redis:latest
    networks:
      - rinha-network
    ports:
      - "6379:6379"
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "70MB"
networks:
  rinha-network:
    driver: bridge
  payment-processor:
    external: true