services:

  api01: &app
    image: thiagorigonatti/rinha-2025-scratch:0.0.3
    environment:
      - HTTP_CLIENT_THREADS=6
      - SOCKET_SERVER_THREADS=6
      - SHM_PATH=/shm_array
      - SOCKET_PATH=/dev/shm/server1.sock
    networks:
      - api
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "10MB"
    volumes:
      - shm-vol:/dev/shm


  api02:
    <<: *app
    environment:
      - HTTP_CLIENT_THREADS=6
      - SOCKET_SERVER_THREADS=6
      - SHM_PATH=/shm_array
      - SOCKET_PATH=/dev/shm/server2.sock


  haproxy:
    image: haproxy:3.3-dev5-alpine3.22
    volumes:
      - shm-vol:/dev/shm
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "15MB"
    networks:
      - api
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02


networks:
  api:
    driver: bridge
  payment-processor:
    external: true


volumes:
  shm-vol:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=1m
