services:
  api01: &app
    image: thiagorigonatti/rinha-2025:latest
    environment:
      - PTHREADS=8
    networks:
      - api
      - payment-processor
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "7MB"
    volumes:
      - /dev/shm:/dev/shm

  api02:
    <<: *app
    ports:
      - "8082:8080"

  haproxy:
    image: haproxy:3.3-dev5-alpine3.22
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "100MB"
    networks:
      - api
    ports:
      - "9999:8080"
    depends_on:
      - api01
      - api02

networks:
  api:
    driver: bridge
  payment-processor:
    external: true
