version: '3.9'

services:
  app1: &app
    image: maruero/rinha-de-backend-2025:socket-native
    hostname: app1
    environment:
      - PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
      - OTHER_INSTANCE_URL=http://app2:8080
      - SOCKET=/var/tmp/sockets/app1.sock
      - CONCURRENCY=2
      - WORKER_COUNT=2
    volumes:
      - sockets:/var/tmp/sockets
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "112MB"

  app2:
    <<: *app
    hostname: app2
    environment:
      - PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
      - OTHER_INSTANCE_URL=http://app1:8080
      - SOCKET=/var/tmp/sockets/app2.sock
      - CONCURRENCY=2
      - WORKER_COUNT=2
    volumes:
      - sockets:/var/tmp/sockets
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "112MB"

  haproxy:
    image: haproxy:alpine
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/var/tmp/sockets:rw
    depends_on:
      - app1
      - app2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "124MB"
volumes:
  sockets:
  
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
    name: payment-processor