version: '3.9'

services:
  app1: &app
    image: maruero/rinha-de-backend-2025:v1
    hostname: app1
    environment:
      - PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
      - OTHER_INSTANCE_URL=http://app2:8080
      - CONCURRENCY=2
      - WORKER_COUNT=2
    ports:
      - "8081:8080"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: "167MB"

  app2:
    <<: *app
    hostname: app2
    environment:
      - PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
      - OTHER_INSTANCE_URL=http://app1:8080
      - CONCURRENCY=2
      - WORKER_COUNT=2
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: "167MB"

  haproxy:
    image: haproxy:alpine
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - app1
      - app2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "16MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
    name: payment-processor