services:
  nginx:
    image: nginx:alpine
    hostname: rinha-nginx
    restart: unless-stopped
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-api-1
      - backend-api-2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "16MB"

  backend-api-1: &api
    image: ricassiocosta/rinha-backend-2025-python:latest
    hostname: rinha-backend-api-1
    restart: unless-stopped
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "75MB"

  backend-api-2:
    <<: *api
    hostname: rinha-backend-api-2

  worker-light:
    image: ricassiocosta/rinha-backend-2025-python:latest
    hostname: worker-light
    command: ["python", "-m", "app.worker"]
    restart: unless-stopped
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379/0
      - CONSUMER_NAME=worker-light
      - MAX_PARALLELISM=5
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "48MB"

  worker-heavy:
    image: ricassiocosta/rinha-backend-2025-python:latest
    hostname: worker-heavy
    command: ["python", "-m", "app.worker"]
    restart: unless-stopped
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379/0
      - CONSUMER_NAME=worker-heavy
      - MAX_PARALLELISM=10
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "72MB"

  redis:
    image: redis:7-alpine
    hostname: rinha-redis
    restart: unless-stopped
    command:
      [
        "redis-server",
        "--save",
        "",
        "--appendonly",
        "no",
        "--maxclients",
        "5000",
      ]
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "64MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
