services:
  backend-1:
    image: ghcr.io/micheloliveira-com/rinha-de-backend-2025-dotnet-csharp-redis-r:20250803144807
    hostname: backend-1
    networks:
      - backend
      - payment-processor
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - WORKER_SIZE=10
      - BATCH_SIZE=100
      - ConnectionStrings__default=http://payment-processor-default:8080
      - ConnectionStrings__fallback=http://payment-processor-fallback:8080
      - ConnectionStrings__redis=redis:6379
    healthcheck:
      test: >
        for i in $(seq 1 60); do
          wget -q --tries=1 --spider http://localhost:8080/ && break
          sleep 1
        done
      interval: 1h
      timeout: 70s
      retries: 0
      start_period: 1s
    ports:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "145MB"
  backend-2:
    image: ghcr.io/micheloliveira-com/rinha-de-backend-2025-dotnet-csharp-redis-r:20250803144807
    hostname: backend-2
    networks:
      - backend
      - payment-processor
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - WORKER_SIZE=10
      - BATCH_SIZE=100
      - ConnectionStrings__default=http://payment-processor-default:8080
      - ConnectionStrings__fallback=http://payment-processor-fallback:8080
      - ConnectionStrings__redis=redis:6379
    healthcheck:
      test: >
        for i in $(seq 1 60); do
          wget -q --tries=1 --spider http://localhost:8080/ && break
          sleep 1
        done
      interval: 1h
      timeout: 70s
      retries: 0
      start_period: 1s
    ports:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "145MB"
  redis:
    image: redis:8-alpine
    command: >
      redis-server
      --save ""
      --appendonly no
      --maxmemory 10mb
      --maxmemory-policy allkeys-lru
    networks:
      - backend
    ports:
      - "6379"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"
  load-balancer:
    image: haproxy:3.2.3-alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      backend-1:
        condition: service_healthy
      backend-2:
        condition: service_healthy
    ports:
      - "9999:9999"
    networks:
      - backend
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
