services:
  api1: &api
    image: joaoulian/rinha-backend-2025-api:latest
    command: node dist/index.js
    hostname: api1
    environment:
      - PORT=9999
      - REDIS_URL=redis://cache:6379
      - DATABASE_URL=postgresql://docker:docker@database:5432/rinha_de_backend_2025
    networks:
      - backend
      - payment-processor
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_started
      migration:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "350MB"

  api2:
    <<: *api
    hostname: api2

  worker:
    image: joaoulian/rinha-backend-2025-api:latest
    command: node dist/worker.js
    hostname: worker
    environment:
      - REDIS_URL=redis://cache:6379
      - DATABASE_URL=postgresql://docker:docker@database:5432/rinha_de_backend_2025
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_started
      migration:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "350MB"

  migration:
    image: joaoulian/rinha-backend-2025-migration:latest
    command: pnpm db:migrate
    networks:
      - backend
    environment:
      - DATABASE_URL=postgresql://docker:docker@database:5432/rinha_de_backend_2025
    depends_on:
      database:
        condition: service_healthy
    restart: "no"
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "350MB"

  database:
    image: postgres:alpine
    ports:
      - "5482:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rinha_de_backend_2025
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d rinha_de_backend_2025"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "350MB"

  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "350MB"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "42MB"

volumes:
  redis_data:
  database_data:

networks:
  backend:
    driver: bridge
  payment-processor:
    name: payment-processor
    external: true
