version: "3.8"

services:
  api1:
    image: jorgedevsoftware/jorge-rinha:2.0
    container_name: api1
    environment:
     - URL_INSTANCE=http://api2:8080/payments-summary/internal
    ports:
      - "8081:8080"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "110MB"

  api2:
    image: jorgedevsoftware/jorge-rinha:2.0
    container_name: api2
    environment:
     - URL_INSTANCE=http://api1:8080/payments-summary/internal
    ports:
      - "8082:8080"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "110MB"

 
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "9999:80"       
    depends_on:
      - api1
      - api2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus:    "0.20"
          memory:  "35MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    driver: bridge
