services:
  lb:
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 60M
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /tmp:/tmp
    ports:
      - "9999:9999"
    command: >
      sh -c '
        echo "Await app1 and app2...";
        until curl -fs --unix-socket /tmp/unix-app1.sock http://localhost/healthcheck; do
          echo "Await app-1...";
          sleep 0.2;
        done;
        until curl -fs --unix-socket /tmp/unix-app2.sock http://localhost/healthcheck; do
          echo "Await app-2...";
          sleep 0.2;
        done;
        echo "All ready! init NGINX...";
        nginx -g "daemon off;";
      '
    depends_on:
      - app-1
      - app-2

  app-1:
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 70M
    image: daviddeltasierra/rinha-2025-go-2:1.25
    volumes:
      - /tmp:/tmp
    environment:
      - SOCK=/tmp/unix-app1.sock
      - WORKERS=100
      - GOMAXPROCS=1
    depends_on:
      - postgres

  app-2:
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 70M
    image: daviddeltasierra/rinha-2025-go-2:1.25
    volumes:
      - /tmp:/tmp
    environment:
      - SOCK=/tmp/unix-app2.sock
      - WORKERS=100
      - GOMAXPROCS=1
    depends_on:
      - postgres

  postgres:
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 150M
    image: postgres:alpine
    user: postgres
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - /tmp:/var/run/postgresql
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rinha

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true