services:
  app-1:
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 100M
    image: daviddeltasierra/rinha-2025-go-2:1.1
    volumes:
      - socket-volume:/socket
    environment:
      - MASTER=true
    depends_on:
      - postgres
      - app-2
    ports:
      - "9999:8080"

  app-2:
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 100M
    image: daviddeltasierra/rinha-2025-go-2:1.1
    volumes:
      - socket-volume:/socket
    environment:
      - MASTER=false
    depends_on:
      - postgres

  postgres:
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 150M
    image: postgres:alpine
    user: postgres
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rinha

volumes:
  socket-volume:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true