services:
  api-1: &api
    image: gustavotbett/rinha-backend-2025-api:20250805-005411
    hostname: api
    networks:
      - internal
      - payment-processor
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    depends_on:
      - redis
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "125MB"

  api-2:
    <<: *api
    hostname: api-2

  nginx:
    image: nginx:1.28.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - payment-processor
      - internal
    depends_on:
      api-1:
        condition: service_healthy
      api-2:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  redis:
    image: redis:8.0.3-alpine
    container_name: redis
    command: [ "redis-server", "--maxmemory", "80mb", "--maxmemory-policy", "allkeys-lru" ]
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "80MB"

networks:
  internal:
    driver: bridge
  payment-processor:
    external: true