name : payment-proxy

x-service-templates:
  base: &apibase
    image: acslook/payment-proxy:v4

services:  
  redis:
    container_name: redis
    image: redis:8-alpine
    ports:
      - "6379:6379"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: "90MB"
  db:
    image: postgres:17-alpine
    container_name: payment-db
    hostname: db
    environment:
      - POSTGRES_PASSWORD=rinha25
      - POSTGRES_USER=rinha25
      - POSTGRES_DB=payments_db
    ports:
      - "5432:5432"
    command: >
      postgres 
        -c max_connections=400 
        -c shared_buffers=128MB 
        -c effective_cache_size=256MB 
        -c work_mem=8MB 
        -c maintenance_work_mem=12MB 
        -c synchronous_commit=off 
        -c full_page_writes=off
        -c fsync=off
        -c log_min_messages=panic
    networks:
      - backend
      - payment-processor
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "130MB"
  api1:
      <<: *apibase
      container_name: api1
      environment:
        - CONN_STRING=postgres://rinha25:rinha25@db:5432/payments_db?sslmode=disable
        - REDIS_URL=redis:6379
        - GATEWAY_DEFAULT_URL=http://payment-processor-default:8080
        - GATEWAY_FALLBACK_URL=http://payment-processor-fallback:8080
      networks:
        - backend
        - payment-processor
      restart: unless-stopped
      command: ["server"]
      deploy:
        resources:
          limits:
            cpus: '0.2'
            memory: "10MB"
      depends_on:
        - db
        - redis
  api2:
    <<: *apibase
    container_name: api2
    environment:
      - CONN_STRING=postgres://rinha25:rinha25@db:5432/payments_db?sslmode=disable
      - REDIS_URL=redis:6379
      - GATEWAY_DEFAULT_URL=http://payment-processor-default:8080
      - GATEWAY_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    restart: unless-stopped
    command: ["server"]
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: "10MB"
    depends_on:
      - db
      - redis

  worker:
      <<: *apibase
      container_name: worker
      environment:
        - CONN_STRING=postgres://rinha25:rinha25@db:5432/payments_db?sslmode=disable
        - REDIS_URL=redis:6379
        - GATEWAY_DEFAULT_URL=http://payment-processor-default:8080
        - GATEWAY_FALLBACK_URL=http://payment-processor-fallback:8080
      networks:
        - backend
        - payment-processor
      restart: unless-stopped
      command: ["worker"]
      deploy:
        resources:
          limits:
            cpus: '0.2'
            memory: "60MB"
      depends_on:
        - db
        - redis
  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
      - worker
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: "50MB"
    networks:
      - backend
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true