x-app-config: &app-config
  image: jvcouto/jvpayments:2.0
  depends_on:
    redis:
      condition: service_healthy
  environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - PAYMENT_API_URL=http://payment-processor-default:8080
    - PAYMENT_API_FALLBACK_URL=http://payment-processor-fallback:8080
  volumes:
    - socket_data:/tmp/sockets
  networks:
    - app
    - payment-processor
  deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "125MB"

services:
  jvpayments-1:
    <<: *app-config
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PAYMENT_API_URL=http://payment-processor-default:8080
      - PAYMENT_API_FALLBACK_URL=http://payment-processor-fallback:8080
      - SOCKET_PATH=/tmp/sockets/jvpayments-1.sock

  jvpayments-2:
    <<: *app-config
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PAYMENT_API_URL=http://payment-processor-default:8080
      - PAYMENT_API_FALLBACK_URL=http://payment-processor-fallback:8080
      - SOCKET_PATH=/tmp/sockets/jvpayments-2.sock

  haproxy:
    image: haproxy:alpine
    ports:
      - "9999:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - socket_data:/tmp/sockets
    depends_on:
      - jvpayments-1
      - jvpayments-2
    networks:
      - app
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  redis:
    image: redis:7-alpine
    command: redis-server --save "" --appendonly no
    ports:
      - "6379:6379"
    networks:
      - app
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

volumes:
  socket_data:

networks:
  app:
    driver: bridge
  payment-processor:
    external: true
