services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - rinha-backend
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "15MB"

  api1: &api
    image: ghcr.io/mourishitz/go-proxy:latest
    container_name: api-1
    hostname: api1
    restart: always
    environment:
      - APP_PORT=8080
      - KEYDB_SERVICE_URL=keydb:6379
      - INSTANCE_ID=1
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "30MB"
    networks:
      - rinha-backend
    depends_on:
      - keydb

  api2:
    <<: *api
    container_name: api-2
    hostname: api2
    environment:
      - APP_PORT=8080
      - KEYDB_SERVICE_URL=keydb:6379
      - INSTANCE_ID=2

  keydb:
    image: eqalpha/keydb:alpine
    container_name: keydb
    ports:
      - "6379:6379"
    networks:
      - rinha-backend
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "200MB"

  worker1: &worker
    container_name: worker-1
    hostname: worker1
    image: ghcr.io/mourishitz/go-worker:latest
    restart: always
    environment:
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - KEYDB_SERVICE_URL=keydb:6379
      - INSTANCE_ID=worker-1
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "25MB"
    networks:
      - rinha-backend
      - payment-processor
    depends_on:
      - keydb

  worker2:
    <<: *worker
    container_name: worker-2
    hostname: worker2
    environment:
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - KEYDB_SERVICE_URL=keydb:6379
      - INSTANCE_ID=worker-2
    depends_on:
      - keydb

  worker3:
    <<: *worker
    container_name: worker-3
    hostname: worker3
    environment:
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - KEYDB_SERVICE_URL=keydb:6379
      - INSTANCE_ID=worker-3
    depends_on:
      - keydb

networks:
  rinha-backend:
    name: rinha-backend
    driver: bridge
  payment-processor:
    external: true
