services:
  nginx:
    image: nginx:1.25-alpine
    platform: linux/amd64
    container_name: nginx
    volumes:
      - ./nginx.config:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"     
          memory: "30MB"    

  api1: &api
    image: juliopeixoto/rinha-fastapi:latest    
    platform: linux/amd64
    hostname: api1
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.60"      
          memory: "145MB"   

  api2:
    <<: *api
    hostname: api2
    environment:
      - REDIS_URL=redis://redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080

  redis:
    image: redis:7.2-alpine
    platform: linux/amd64
    container_name: redis
    command: redis-server --save "" --appendonly
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 2s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.15"      
          memory: "30MB"    

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
    name: payment-processor 