services:
  nginx:
    image: nginx:1.29.0-alpine
    container_name: rinha-nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/sockets:rw
    ports:
      - "9999:80"
    networks:
      - backend
    depends_on:
      - rinha-gateway-1
      - rinha-gateway-2
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "50MB"

  rinha-gateway-1:
    image: ghcr.io/alan-venv/rinha-gateway:latest
    pull_policy: always
    container_name: rinha-gateway-1
    env_file:
      - ./config/.env
    environment:
      - SOCKET=/sockets/gateway-1.sock
    volumes:
      - sockets:/sockets:rw
    networks:
      - backend
      - payment-processor
    depends_on:
      - rinha-database
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  rinha-gateway-2:
    image: ghcr.io/alan-venv/rinha-gateway:latest
    pull_policy: always
    container_name: rinha-gateway-2
    env_file:
      - ./config/.env
    environment:
      - SOCKET=/sockets/gateway-2.sock
    volumes:
      - sockets:/sockets:rw
    networks:
      - backend
      - payment-processor
    depends_on:
      - rinha-database
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  rinha-gateway-3:
    image: ghcr.io/alan-venv/rinha-gateway:latest
    pull_policy: always
    container_name: rinha-gateway-3
    env_file:
      - ./config/.env
    environment:
      - SOCKET=/sockets/gateway-3.sock
    volumes:
      - sockets:/sockets:rw
    networks:
      - backend
      - payment-processor
    depends_on:
      - rinha-database
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  rinha-database:
    image: ghcr.io/alan-venv/rinha-database:latest
    pull_policy: always
    container_name: rinha-database
    volumes:
      - sockets:/sockets:rw
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=16m,mode=1777

networks:
  backend:
    name: rinha-net
    driver: bridge
  payment-processor:
    external: true
