services:
  nginx:
    image: nginx:1.29.0-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/sockets:rw
    ports:
      - "9999:80"
    networks:
      - backend
    depends_on:
      - rinha-gateway-1
      - rinha-gateway-2
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  rinha-gateway-1:
    image: ghcr.io/alan-venv/rinha-gateway:6.0
    container_name: rinha-gateway-1
    volumes:
      - sockets:/sockets:rw
    environment:
      - SOCKET_PATH=/sockets/actix.sock.1
    networks:
      - backend
      - payment-processor
    depends_on:
      - rinha-db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "125MB"

  rinha-gateway-2:
    image: ghcr.io/alan-venv/rinha-gateway:6.0
    container_name: rinha-gateway-2
    volumes:
      - sockets:/sockets:rw
    environment:
      - SOCKET_PATH=/sockets/actix.sock.2
    networks:
      - backend
      - payment-processor
    depends_on:
      - rinha-db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "125MB"

  rinha-db:
    image: ghcr.io/alan-venv/rinha-database:6.0
    container_name: rinha-db
    volumes:
      - sockets:/sockets:rw
    environment:
      - SOCKET_PATH=/sockets/database.sock
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

volumes:
  sockets:

networks:
  backend:
    name: rinha-net
    driver: bridge
  payment-processor:
    external: true
