services:
  haproxy:
    image: haproxy:3.2.3-alpine
    container_name: rinha-haproxy
    ports:
      - 9999:80
    volumes:
      - sockets:/sockets:rw
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - backend
    depends_on:
      - rinha-gateway-1
      - rinha-gateway-2
      - rinha-gateway-3
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "80MB"

  rinha-gateway-1:
    image: ghcr.io/alan-venv/rinha-gateway:6.8-skylake
    container_name: rinha-gateway-1
    environment:
      - SOCKET=/sockets/actix.sock.1
      - TRIGGER=${TRIGGER}
      - SLAVES=${SLAVES}
      - ANALYST=${ANALYST}
    volumes:
      - sockets:/sockets:rw
    networks:
      - backend
      - payment-processor
    depends_on:
      - rinha-database
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "70MB"

  rinha-gateway-2:
    image: ghcr.io/alan-venv/rinha-gateway:6.8-skylake
    container_name: rinha-gateway-2
    environment:
      - SOCKET=/sockets/actix.sock.2
      - TRIGGER=${TRIGGER}
      - SLAVES=${SLAVES}
      - ANALYST=${ANALYST}
    volumes:
      - sockets:/sockets:rw
    networks:
      - backend
      - payment-processor
    depends_on:
      - rinha-database
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "70MB"

  rinha-gateway-3:
    image: ghcr.io/alan-venv/rinha-gateway:6.8-skylake
    container_name: rinha-gateway-3
    environment:
      - SOCKET=/sockets/actix.sock.3
      - TRIGGER=${TRIGGER}
      - SLAVES=${SLAVES}
      - ANALYST=${ANALYST}
    volumes:
      - sockets:/sockets:rw
    networks:
      - backend
      - payment-processor
    depends_on:
      - rinha-database
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "70MB"

  rinha-database:
    image: ghcr.io/alan-venv/rinha-database:6.5-skylake
    container_name: rinha-database
    volumes:
      - sockets:/sockets:rw
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

volumes:
  sockets:

networks:
  backend:
    name: rinha-net
    driver: bridge
  payment-processor:
    external: true
