networks:
  default:
    driver: bridge

services:
  postgres:
    image: postgres:17-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d rinha"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: rinha
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
        - default
    deploy:
      resources:
        limits:
          cpus:   '0.10'
          memory: '128M'
  
  api-1:
    image: 881029/rinha-backend-2025:2.3.2
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HOST: 0.0.0.0
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASS: pass
      DB_NAME: rinha
      PROCESSOR_DEFAULT:  http://host.docker.internal:8001
      PROCESSOR_FALLBACK: http://host.docker.internal:8002
    expose:
      - "9999"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus:   '0.50'
          memory: '81M'

  api-2:
    image: 881029/rinha-backend-2025:2.3.2 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HOST: 0.0.0.0
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASS: pass
      DB_NAME: rinha
      PROCESSOR_DEFAULT:  http://host.docker.internal:8001
      PROCESSOR_FALLBACK: http://host.docker.internal:8002
    expose:
      - "9999"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus:   '0.50'
          memory: '81M'
 
  lb:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:80"
    networks:
      - default
    depends_on:
      - api-1
      - api-2
    deploy:
      resources:
        limits:
          cpus:   '0.40'
          memory: '50M'
volumes:
  postgres-data:
