services:
  backend:
    image: felipeschirmann/rinha-backend-2025:15.0.3
    #    image: rinha-backend:latest
    container_name: felipeschirmann-rinha
    environment:
      # --- Client and Health Check Settings ---
      PAYMENT_PROCESSOR_DEFAULT_URL: "http://payment-processor-default:8080"
      PAYMENT_PROCESSOR_FALLBACK_URL: "http://payment-processor-fallback:8080"
    sysctls:
      net.core.somaxconn: 4096
    ports:
      - "9999:9999"
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "350MB"

networks:
  payment-processor:
    # This assumes the network is created externally by the payment-processor's docker-compose.
    external: true
