services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - backend
    depends_on:
      - api1
      - api2
    sysctls:
      net.core.somaxconn: 65535
      net.ipv4.tcp_tw_reuse: "1"
      net.ipv4.tcp_fin_timeout: "15"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "25MB"

  api1: &api
    image: josiney/rdb25_02-amd64:latest 
    hostname: api1
    networks:
      - backend
      - payment-processor 
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PORT=9997
      - PAYMENTS_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments
      - PAYMENTS_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments
      - HEALTH_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments/service-health
      - HEALTH_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments/service-health
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "40MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PORT=9998
      - PAYMENTS_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments
      - PAYMENTS_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments
      - HEALTH_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments/service-health
      - HEALTH_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments/service-health

  redis:
    image: redis/redis-stack:7.2.0-v18
    hostname: rinha-redis
    environment:
      - REDISTIMESERIES_ARGS=DUPLICATE_POLICY=SUM
    networks:
      - backend
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 5s
      retries: 20
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "75MB" 

networks:
  backend:
    name: rinha-backend
    driver: bridge
  payment-processor:
    external: true 
