services:
  api01: &api
    image: distanteagle16/rinhabackend3-api:1.3.0
    restart: always
    hostname: api01
    networks:
      - payment-processor
      - backend
    depends_on:
      worker:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      QUEUE_BACKOFF: 1
      DATABASE_URL: postgresql://postgres:postgres@db:5432/db
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"
    volumes:
      - sockets:/tmp/sockets

  api02:
    <<: *api
    hostname: api02

  worker:
    image: distanteagle16/rinhabackend3-worker:1.3.0
    restart: always
    networks:
      - payment-processor
      - backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      CHANNEL_THREADS: 40
      WORKER_THREADS: 4
      DATABASE_URL: postgresql://postgres:postgres@db:5432/db
      PAYMENT_PROCESSOR_URL_DEFAULT: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_URL_FALLBACK: http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "60MB"
    volumes:
      - sockets:/tmp/sockets

  lb:
    image: distanteagle16/rinhabackend3-raijin-lb:1.3.0
    restart: always
    environment:
      LISTEN_ADDR: 0.0.0.0:9999
      MIN_PERSISTENT_CONNECTIONS: 8
      MAX_PERSISTENT_CONNECTIONS: 340
      TARGET_SOCKETS: /tmp/sockets/api01.sock,/tmp/sockets/api02.sock
    networks:
      - backend
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    volumes:
      - sockets:/tmp/sockets
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '40MB'

  postgres:
    image: timescale/timescaledb-ha:pg17
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./assets/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./assets/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '210MB'

networks:
  backend:
    name: backend
    driver: bridge
  payment-processor:
    external: true

volumes:
  sockets: