x-service-templates:
  api: &api
    image: mkonita/rinha2025-node:1.0.3
    networks:
      - internal
      - payment-processor
    depends_on:
      - keydb
    environment:
      PORT: 3000
      KEYDB_HOST: 'keydb'
      QUEUE_SIZE: 200
      CONCURRENCY: 25
      CONNECTIONS: 1
      PIPELINING: 16
      PAYMENT_URL_DEFAULT: http://payment-processor-default:8080
      PAYMENT_URL_FALLBACK: http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "130MB"

services:
  api1:
    <<: *api
    container_name: api1
    hostname: api1

  api2:
    <<: *api
    container_name: api2
    hostname: api2

  load-balance:
    image: nginx:alpine
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - internal
    depends_on:
      - api1
      - api2
    ports:
      - "9999:80"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

  keydb:
    image: eqalpha/keydb:latest
    container_name: keydb
    networks:
      - internal
    ports:
      - "6379:6379"
    command: >
      keydb-server /etc/keydb/keydb.conf
      --save ""                     
      --appendonly no               
      --maxmemory 55mb              
      --maxmemory-policy allkeys-lru 
      --tcp-backlog 128             
      --timeout 0                   
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "60MB"

networks:
  internal:
    driver: bridge
  payment-processor:
    external: true
