services:
  redis:
    image: redis:8-alpine
    command: redis-server --save "" --appendonly no --maxmemory 60mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "30M"
    networks:
      - backend

  app1:
    image: pedrohsbarbosa99/rinha-golang-2025:0.1.1
    networks:
      - backend
      - payment-processor
    environment:
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 140M

  app2:
    image: pedrohsbarbosa99/rinha-golang-2025:0.1.1
    command: ["./main"]
    networks:
      - backend
      - payment-processor
    environment:
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 140M

  nginx:
    image: nginx:latest
    container_name: nginx-1
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 30M

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
