services:
  memdb:
    image: pedrohsbarbosa99/rinha-golang-2025:0.1.6
    args:
      APP_ENTRY: ./cmd/database
      OUTPUT_NAME: memdb
    command: ["./memdb"]
    volumes:
      - memsock:/tmp
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 60M
    restart: unless-stopped

  app1:
    image: pedrohsbarbosa99/rinha-golang-2025:0.1.6
    args:
      APP_ENTRY: ./cmd/api
      OUTPUT_NAME: main
    command: ["./main"]
    volumes:
      - memsock:/tmp
    networks:
      - backend
      - payment-processor
    environment:
      - MEMDB_SOCKET=/tmp/kvstore.sock
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    depends_on:
      - memdb
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 140M
    restart: unless-stopped

  app2:
    image: pedrohsbarbosa99/rinha-golang-2025:0.1.6
    args:
      APP_ENTRY: ./cmd/api
      OUTPUT_NAME: main
    command: ["./main"]
    volumes:
      - memsock:/tmp
    networks:
      - backend
      - payment-processor
    environment:
      - MEMDB_SOCKET=/tmp/kvstore.sock
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    depends_on:
      - memdb
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 140M
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx-1
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 30M
    restart: unless-stopped

volumes:
  memsock:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
