x-backend-templates:
  app: &app
    image: csouzadocker/rinha-native-pgo:v0.0.4
    depends_on:
      backend-db:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 1
        window: 5s
      resources:
        limits:
          cpus: "0.65"
          memory: "100MB"

  app-cmd: &app-cmd
    - "./app-optimized"
    - "-DBATCH_SIZE=100"
    - "-DBATCH_LIMIT=10"
    - "-DDATASOURCE_CLASS_NAME=org.postgresql.Driver"
    - "-DDATASOURCE_MAXIMUM_POOL_SIZE=3"
    - "-DDATASOURCE_MINIMUM_IDLE=3"
    - "-DDATASOURCE_PASSWORD=rinha"
    - "-DDATASOURCE_TIMEOUT=20000"
    - "-DDATASOURCE_URL=jdbc:postgresql://postgres:5432/rinha"
    - "-DDATASOURCE_USERNAME=rinha"
    - "-DPAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080"
    - "-DPAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080"
    - "-DPAYMENT_PROCESSOR_WORKERS=10"
    - "-DPAYMENT_PROCESSOR_REQUEST_TIMEOUT=6000"
    - "-DPAYMENT_PROCESSOR_CONNECTION_TIMEOUT=30"
    - "-DSERVER_PORT=8080"
    - "-DSERVER_IO_THREADS=6"
    - "-DSERVER_WORKER_THREADS=2"

#############################################################################################

services:
  nginx:
    image: nginx:alpine
    container_name: backend-nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

  app1:
    <<: *app
    container_name: backend-api1
    hostname: app1
    command: *app-cmd

  app2:
    <<: *app
    container_name: backend-api2
    hostname: app2
    command: *app-cmd

  backend-db:
    image: postgres:17-alpine
    container_name: backend-db
    hostname: postgres
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
    volumes:
      - ./init.sql/init-backend-db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init.sql/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U rinha -d rinha" ]
      interval: 3s
      timeout: 3s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "130MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
