services:      
  nginx:
    image: nginx:alpine
    platform: "linux/amd64"
    depends_on:
      - rinhabackend.api1
      - rinhabackend.api2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"
    networks:
      - frontdoor
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:80"

  rinhabackend.api1:
    image: ghcr.io/alansouls/rinhabackend.api:main
    platform: "linux/amd64"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "100MB"
    networks:
      - backend

  rinhabackend.api2:
    image: ghcr.io/alansouls/rinhabackend.api:main
    platform: "linux/amd64"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "100MB"
    networks:
      - backend
      
  rinhabackend.worker:
    image: ghcr.io/alansouls/rinhabackend.worker:main
    platform: "linux/amd64"
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "100MB"
    networks:
      - backend
      - payment-processor

networks:
  frontdoor:
    # Specify driver options
    driver: bridge
  backend:
    # Specify driver options
    driver: bridge
  payment-processor:
      external: true

