services:

  db_pg:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db_pg-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    shm_size: 128mb
    container_name: db_pg
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: "200MB"

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - go_rinha_1
      - go_rinha_2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: "50MB"

  go_rinha_1: &go_rinha_template
    image: ghcr.io/lucaslimafernandes/rinha-backend-2025-go:v1.4.0
    container_name: go_rinha_1
    networks:
      - backend
      - payment-processor
    depends_on:
      db_pg:
        condition: service_healthy
    restart: always
    expose:
      - "9999"
    environment:
      - PG_DSN=user=postgres password=password host=db_pg port=5432 dbname=postgres sslmode=disable
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: "50MB"

  go_rinha_2:
    <<: *go_rinha_template
    container_name: go_rinha_2

volumes:
  db_pg-data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true  