services:

  nginx:
    image: nginx:alpine
    container_name: nginx-loadbalancer
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rinhaquark2025-a
      - rinhaquark2025-b
    networks:
      - rinhaquark-rede
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "10MB"

  rinhaquark2025-a: &rinhaquark2025
    image: kauanmocelin/rinhaquark2025:1.0.4
    container_name: rinhaquark2025-a
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongo:27017
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - rinhaquark-rede
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "80MB"

  rinhaquark2025-b:
    <<: *rinhaquark2025
    container_name: rinhaquark2025-b

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongod.conf:/etc/mongod.conf:ro
      - mongo-data:/data/db
    command: [ "mongod", "--config", "/etc/mongod.conf" ]
    networks:
      - rinhaquark-rede
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "180MB"
    healthcheck:
      test: [ "CMD-SHELL", "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --quiet" ]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  mongo-data:

networks:
  rinhaquark-rede:
    driver: bridge
  payment-processor:
    external: true