services:
  service1:
    image: willian666/rinha-back-node-2025:latest
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_HOST=redis
      - HEALTH_CHECK_ENABLED=1
      - NODE_ENV=production
    networks:
      - backend
      - payment-processor
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "105MB"

  service2:
    image: willian666/rinha-back-node-2025:latest
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_HOST=redis
      - NODE_ENV=production
    networks:
      - backend
      - payment-processor
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "105MB"

  redis:
    image: redis:8.2-rc1-alpine
    restart: unless-stopped
    container_name: redis
    ports:
    - 6379:6379
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "80MB"
    networks:
      - backend
  
  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - service1
      - service2
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "60MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true