x-service-templates:
  api: &api
    image: flads/rinha25-php-go-api:0.1.2
    networks:
      - main-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "50MB"
  worker: &worker
    image: flads/rinha25-php-go-worker:0.0.1
    container_name: worker
    networks:
      - main-network
      - payment-processor
    depends_on:
      redis:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "100MB"

services:
  api-1:
    <<: *api
    container_name: api-1

  api-2:
    <<: *api
    container_name: api-2

  worker-1:
    <<: *worker
    container_name: worker-1

  worker-2:
    <<: *worker
    container_name: worker-2

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - main-network
    depends_on:
      api-1:
        condition: service_started
      api-2:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "20MB"

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - main-network
    command: ["redis-server"]
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "30MB"

networks:
  main-network:
    driver: bridge
  payment-processor:
    external: true