x-service-templates:
  api: &api
    image: flads/rinha25-php-go-api:0.1.2
    networks:
      - main-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "45MB"
  worker: &worker
    image: flads/rinha25-php-go-worker:0.0.2
    container_name: worker
    networks:
      - main-network
      - payment-processor
    depends_on:
      redis:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "90MB"

services:
  api-1:
    <<: *api
    container_name: api-1

  api-2:
    <<: *api
    container_name: api-2

  worker-1:
    <<: *worker
    container_name: worker-1

  worker-2:
    <<: *worker
    container_name: worker-2

  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "9999:9999"
    networks:
      - main-network
    depends_on:
      api-1:
        condition: service_started
      api-2:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - main-network
    command: ["redis-server"]
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

networks:
  main-network:
    driver: bridge
  payment-processor:
    external: true