x-service-templates:
  api: &api
    image: ghcr.io/leoralph/rinha-de-backend-2025-api:v2.0.3
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.245"
          memory: "110M"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.12"
          memory: "50M"

  redis:
    image: redis:latest
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.28"
          memory: "55M"

  payment-worker:
    image: ghcr.io/leoralph/rinha-de-backend-2025-worker:v2.0.3
    environment:
      - WORKER_TYPE=payment
      - WORKER_COUNT=3
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "15M"

  health-worker:
    image: ghcr.io/leoralph/rinha-de-backend-2025-worker:v2.0.3
    environment:
      - WORKER_TYPE=health
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.01"
          memory: "10M"

  api01:
    <<: *api

  api02:
    <<: *api

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
