x-api_template: &api_template
  image: andersongomes001/rinha-api-2025:latest
  environment:
    PAYMENT_PROCESSOR_DEFAULT_URL: "http://payment-processor-default:8080"
    PAYMENT_PROCESSOR_FALLBACK_URL: "http://payment-processor-fallback:8080"
    REDIS_URL: "redis://redis:6379/"
    PORT: 80
  networks:
    - backend
    - payment-processor
  deploy:
    resources:
      limits:
        cpus: "0.3"
        memory: "80MB"
services:
  api01:
    <<: *api_template
    hostname: api01
    depends_on:
      - redis
  api02:
    <<: *api_template
    hostname: api02
    depends_on:
      - redis
  redis:
    image: redis:8.0.3-alpine
    hostname: redis
    networks:
      - backend
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no", "--save", ""]
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:80"
    depends_on:
      - api01
      - api02
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "90MB"
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
