x-api_template: &api_template
  image: andersongomes001/rinha-api-2025:d7f3af1
  networks:
    - backend
    - payment-processor
  deploy:
    resources:
      limits:
        cpus: "0.5"
        memory: "100MB"

services:
  api01:
    <<: *api_template
    hostname: api01
    environment:
      PAYMENT_PROCESSOR_DEFAULT_URL: "http://payment-processor-default:8080"
      PAYMENT_PROCESSOR_FALLBACK_URL: "http://payment-processor-fallback:8080"
      REDIS_URL: "redis://redis:6379/"
      PORT: 80
      INSTANCE_ROLE: "master"
      MAX_WORKERS: 7
    depends_on:
      - redis
  api02:
    <<: *api_template
    hostname: api02
    environment:
      PAYMENT_PROCESSOR_DEFAULT_URL: "http://payment-processor-default:8080"
      PAYMENT_PROCESSOR_FALLBACK_URL: "http://payment-processor-fallback:8080"
      REDIS_URL: "redis://redis:6379/"
      PORT: 80
      INSTANCE_ROLE: "slave"
      WS_MASTER_URL: "ws://api01:9001"
      MAX_WORKERS: 7
    depends_on:
      - redis
      - api01
  redis:
    image: redis:8.0.3-alpine
    hostname: redis
    networks:
      - backend
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no", "--save", ""]
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:80"
    depends_on:
      - api01
      - api02
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"

networks:
  backend:
  payment-processor:
    external: true
