version: "3.5"
x-service-templates:
  payment-processor: &payment-processor
    image: zanfranceschi/payment-processor:amd64-20250707101540
    networks:
      - payment-processor
      - payment-processor-db
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "100MB"

  payment-processor-db: &payment-processor-db
    image: postgres:17-alpine
    networks:
      - payment-processor-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "250MB"

services:
  api01: &api
    image: ghcr.io/marincor/rinha-backend-2025-golang:latest
    environment:
      SERVER_PORT: 5000
      PAYMENT_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080
      PAYMENT_PROCESSOR_DEFAULT: http://payment-processor-default:8080
      REDIS_URL: redis:6379
    networks:
      - payment-processor
      - redis-network
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "135MB"

  api02:
    <<: *api
    hostname: api02

  redis:
    image: redis:8.0.3-alpine
    hostname: redis
    networks:
      - redis-network
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec"]
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    networks:
      - payment-processor
      - redis-network
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

  payment-processor-1:
    <<: *payment-processor
    container_name: payment-processor-default
    hostname: payment-processor-default
    environment:
      - TRANSACTION_FEE=0.05
      - RATE_LIMIT_SECONDS=5
      - INITIAL_TOKEN=123
      - DB_CONNECTION_STRING=Host=payment-processor-default-db;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    ports:
      - 8001:8080
    depends_on:
      - payment-processor-db-1

  payment-processor-db-1:
    <<: *payment-processor-db
    container_name: payment-processor-default-db
    hostname: payment-processor-default-db

  payment-processor-2:
    <<: *payment-processor
    container_name: payment-processor-fallback
    hostname: payment-processor-fallback
    environment:
      - TRANSACTION_FEE=0.15
      - RATE_LIMIT_SECONDS=5
      - INITIAL_TOKEN=123
      - DB_CONNECTION_STRING=Host=payment-processor-fallback-db;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    ports:
      - 8002:8080
    networks:
      - payment-processor
      - payment-processor-db
    depends_on:
      - payment-processor-db-2

  payment-processor-db-2:
    <<: *payment-processor-db
    container_name: payment-processor-fallback-db
    hostname: payment-processor-fallback-db

networks:
  payment-processor:
    name: payment-processor
    driver: bridge
  payment-processor-db:
    driver: bridge
  redis-network:
    driver: bridge