x-service-templates:
  backend-service: &backend-service
    image: ghcr.io/4emcos/rinha-backend-2025-golang:1.0.7
    environment: &backend-env
      APP_PORT: 5000
      PAYMENT_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080
      PAYMENT_PROCESSOR_DEFAULT: http://payment-processor-default:8080
      WRITER_HOST: writer:6666
    networks:
      - payment-processor
      - backend
      - writer-network
    depends_on:
      - writer
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "115MB"

services:
  backend-01:
    <<: *backend-service
    container_name: backend-01
    hostname: backend-01

  backend-02:
    <<: *backend-service
    container_name: backend-02
    hostname: backend-02

  writer:
    hostname: writer
    image: ghcr.io/4emcos/writer:1.0.1
    networks:
      - writer-network
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "85MB"

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    volumes:
      - ./devops/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      backend-01:
        condition: service_healthy
      backend-02:
        condition: service_healthy
    networks:
      - backend
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "25MB"

networks:
  backend:
    driver: bridge
  writer-network:
    driver: bridge
  payment-processor:
    external: true