version: "3.5"

services:
  api01: &api
    image: ghcr.io/4emcos/rinha-backend-2025-golang:latest
    hostname: api01
    environment:
      APP_PORT: 5000
      PAYMENT_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080
      PAYMENT_PROCESSOR_DEFAULT: http://payment-processor-default:8080
      REDIS_URL: redis:6379
    networks:
      - payment-processor
      - redis-network
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "70MB"

  api02:
    <<: *api
    hostname: api02

  redis:
    image: redis:8.0.3-alpine
    hostname: redis
    networks:
      - redis-network
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec"]
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./devops/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    networks:
      - payment-processor
      - redis-network
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "15MB"

networks:
  payment-processor:
    name: payment-processor
    driver: bridge
    external: true
  payment-processor-db:
    driver: bridge
  redis-network:
    driver: bridge