x-app-template:
  api: &api
    image: wendelllsc/rinha_backend_2025_01:latest
    networks:
      - backend
      - payment-processor
    depends_on:
      postgres:
        condition: service_healthy
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "125MB"

  app-env: &app-env
    SERVER_PORT: "8080"
    URL_PROCESSOR_DEFAULT_PAYMENT: "http://payment-processor-default:8080/payments"
    URL_PROCESSOR_FALLBACK_PAYMENT: "http://payment-processor-fallback:8080/payments"
    ACTIVE_PROFILE: "dev"
    DB_URL: "jdbc:postgresql://postgres:5432/rinha"
    DB_USER: "rinha"
    DB_PASS: "rinha"
    WORKER_POOL_SIZE: 35
    CLIENT_MAX_CONNECTIONS: 200
    QUEUE_SIZE: 12000
    PROCESSOR_MAX_RETRIES: 10
    JAVA_TOOL_OPTIONS: >
      --enable-preview
      -server
      -XX:+UseZGC
      -XX:+DisableExplicitGC
      -XX:+AlwaysPreTouch
      -XX:+TieredCompilation
      -XX:TieredStopAtLevel=1

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_api
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U rinha -d rinha" ]
      interval: 3s
      timeout: 3s
      retries: 10
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "85MB"
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "15MB"

  api1:
    <<: *api
    container_name: api1
    hostname: api1
    environment:
      <<: *app-env

  api2:
    <<: *api
    container_name: api2
    hostname: api2
    environment:
      <<: *app-env

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true