x-service-templates:
  base: &base
    image: ghcr.io/leorcvargas/rinha-de-backend-2025-elixir:20250813010132
    volumes:
      - sockets:/tmp/rinhex/:rw
    networks:
      - payment-processor
      - rinhex

services:
  loadbalancer:
    image: openresty/openresty:bullseye
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:rw
      - sockets:/tmp/rinhex/:rw
    depends_on:
      - api1
      - api2
      - worker
    networks:
      - rinhex
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "29MB"

  api1:
    <<: *base
    hostname: api1
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "107MB"
    environment:
      APPLICATION_MODE: "api"
      ERL_MAX_PORTS: 4500
      PAYMENT_PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
      ERL_FLAGS: "+S 1:1 +sbwt none +sbwtdcpu none +sbwtdio none +L"
      UDS_SOCKET: "/tmp/rinhex/api1.sock"

  api2:
    <<: *base
    hostname: api2
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "107MB"
    environment:
      APPLICATION_MODE: "api"
      ERL_MAX_PORTS: 4500
      PAYMENT_PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
      ERL_FLAGS: "+S 1:1 +sbwt none +sbwtdcpu none +sbwtdio none +L"
      UDS_SOCKET: "/tmp/rinhex/api2.sock"

  worker:
    <<: *base
    hostname: worker
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "107MB"
    environment:
      APPLICATION_MODE: "worker"
      ERL_MAX_PORTS: 2048
      PAYMENT_PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
      ERL_FLAGS: "+S 1:1 +sbwt none +sbwtdcpu none +sbwtdio none +L"

volumes:
  sockets:

networks:
  payment-processor:
    external: true
  rinhex:
    driver: bridge
