services:
  rinha:
    platform: "linux/amd64"
    image: "joaoprocopio/rinha:amd64-20250802001327"
    networks:
      - "payment-processor"
    environment:
      RINHA_HOST: "0.0.0.0"
      RINHA_PORT: "9999"
      RINHA_DEFAULT_BACKEND_HOST: "host.docker.internal"
      RINHA_DEFAULT_BACKEND_PORT: "8001"
      RINHA_FALLBACK_BACKEND_HOST: "host.docker.internal"
      RINHA_FALLBACK_BACKEND_PORT: "8002"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "350MB"
        reservations:
          cpus: "1.5"
          memory: "350MB"

networks:
  payment-processor:
    external: true
