services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend-rinha
    deploy:
      resources:
       limits:
          cpus: "0.20"
          memory: "50MB"

  api1: &api
    image: diogoloff/api-fpc-rinha2025:latest
    depends_on:
      - persistencia
    hostname: api1
    environment:
      - DEFAULT_URL=http://payment-processor-default:8080
      - FALLBACK_URL=http://payment-processor-fallback:8080
      - CONSOLIDA_URL=http://persistencia:9090
      - CON_TIME_OUT=5000
      - READ_TIME_OUT=200
      - NUM_WORKERS=16
      - NUM_WORKERS_SOCKET=32
      - NUM_TENTATIVAS_DEFAULT=10
      - TEMPO_FILA=100
    networks:
      - backend-rinha
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.375"
          memory: "50MB"
    
  api2:
    <<: *api
    hostname: api2
  persistencia: 
    image: diogoloff/persistencia-fpc-rinha2025:latest
    hostname: persistencia
    environment:
      - NUM_WORKERS_SOCKET=32
    networks:
      - backend-rinha
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

networks:
  backend-rinha:
    name: backend-rinha
    driver: bridge
  payment-processor:
    external: true
