x-worker-templates:
  worker-backend: &worker-backend
    image: passosmatheus/python-backend-rinha-api-worker:teste-latency-4
    environment:
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080/payments
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080/payments
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '110MB'
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_tw_reuse=1

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-db
    command:
      - redis-server
      - --save ""
      - --appendonly no
      - --maxclients 10000
      - --tcp-backlog 511
      - --tcp-keepalive 60
      - --timeout 0
      - --maxmemory 45mb
      - --maxmemory-policy allkeys-lru
    networks:
      - app
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.12'
          memory: '65MB'

  worker-1:
    <<: *worker-backend
    container_name: worker-1
    networks:
      - app
      - payment-processor
    depends_on:
      - redis

  worker-2:
    <<: *worker-backend
    container_name: worker-2
    networks:
      - app
      - payment-processor
    depends_on:
      - redis

  load-balancer:
    image: nginx:1.25-alpine
    container_name: load-balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      worker-1:
        condition: service_started
      worker-2:
        condition: service_started
    ports:
      - "9999:9999"
      - "9901:9901"
    networks:
      - app
    deploy:
      resources:
        limits:
          cpus: '0.18'
          memory: '65MB'
    sysctls:
      - net.core.somaxconn=131072
      - net.ipv4.tcp_tw_reuse=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/nginx-health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  app:
    driver: bridge
  payment-processor:
    external: true
