services:
  backend-1:
    image: gabxdevv/rinha-backend-2025-java-gabxdev-nginx-final:1.0.1
    restart: always
    environment:
      RETRY_API_DEFAULT: 8
      WORKER_POOL_SIZE: 20
      WORKERS_THREAD_POOL_SIZE: 10
      IO_THREAD_POOL_SIZE: 8
      TIMEOUT_PROFESSOR_DEFAULT: 1100
      TIMEOUT_PROFESSOR_FALLBACK: 1100
      URL_PROCESSOR_DEFAULT: http://payment-processor-default:8080/payments
      URL_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080/payments
      UDP_CHANNEL_INTERNAL_PORT: 9003
      EXTERNAL_UDP_HOST: backend-2
      SERVER_PORT: 8080
      EXTERNAL_UDP_PORT: 9004
      CLIENT_BACKOFF: 250
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '145MB'

  backend-2:
    image: gabxdevv/rinha-backend-2025-java-gabxdev-nginx-final:1.0.1
    restart: always
    environment:
      RETRY_API_DEFAULT: 8
      WORKER_POOL_SIZE: 20
      WORKERS_THREAD_POOL_SIZE: 10
      IO_THREAD_POOL_SIZE: 8
      TIMEOUT_PROFESSOR_DEFAULT: 1100
      TIMEOUT_PROFESSOR_FALLBACK: 1100
      URL_PROCESSOR_DEFAULT: http://payment-processor-default:8080/payments
      URL_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080/payments
      UDP_CHANNEL_INTERNAL_PORT: 9004
      EXTERNAL_UDP_HOST: backend-1
      EXTERNAL_UDP_PORT: 9003
      SERVER_PORT: 8080
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '145MB'

  load-balancer:
    image: nginx:1.28-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-1
      - backend-2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "60MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true