x-backend-templates:
  app: &app
    image: csouzadocker/rinha-2025-redis-native:0.0.2
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "100MB"

  app-env: &app-env
    ACTIVE_MONITOR: "false"
    server.port: "8080"
    PAYMENT_QUEUE: "1000"
    PAYMENT_PROCESSOR_MAX_RETRIES: "5"
    PAYMENT_PROCESSOR_REQUEST_TIMEOUT: "10000"
    PAYMENT_PROCESSOR_WORKERS: "4"
    QUEUE_SIZE: "500"
    QUEUE_IS_FAIR: "true"
    REDIS_HOST: "redis"
    REDIS_WORKERS: "4"
    REQUEST_CONNECTION_TIMEOUT: "50"
    REQUEST_READ_TIMEOUT: "3000"
    THREAD_POOL_SIZE: "10"
    VIRTUAL_THREADS: "true"
    WEBCLIENT_MAX_CONNECTION: "200"
    payment-processor.default.url: "http://payment-processor-default:8080"
    payment-processor.fallback.url: "http://payment-processor-fallback:8080"
    SPRING_APPLICATION_JSON: >
      {
        "spring.threads.virtual.enabled": false,
        "server.servlet.session.persistent": false,
        "server.servlet.session.timeout": 0,
        "server.servlet.session.tracking-modes": [],
        "spring.main.banner-mode": "off",
        "spring.jmx.enabled": false,
        "spring.application.admin.enabled": false,
        "spring.mvc.async.request-timeout": -1,
        "spring.mvc.dispatch-options-request": false,
        "spring.mvc.dispatch-trace-request": false,
        "spring.mvc.log-request-details": false,
        "server.undertow.threads.io": 2,
        "server.undertow.threads.worker": 8,
        "server.undertow.buffer-size": 1024,
        "server.undertow.direct-buffers": true,
        "server.undertow.max-http-post-size": "1KB",
        "server.undertow.no-request-timeout": 2000,
        "spring.mvc.log-resolved-exception": false,
        "logging.level.root": "error",
        "logging.level.br.com.ccs.rinha": "info"              
      }

#####################################################

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "15MB"

  app1:
    <<: *app
    container_name: backend-api1
    hostname: backend-api1
    environment:
      <<: *app-env

  app2:
    <<: *app
    container_name: backend-api2
    hostname: backend-api2
    environment:
      <<: *app-env

  redis:
    image: redis:8.0.3-alpine
    container_name: redis
    hostname: redis
    command: [
      "redis-server",
      "--save", "",
      "--appendonly", "no",
      "--maxmemory", "110mb",
      "--maxmemory-policy", "noeviction",
      "--timeout", "0"
    ]
    ports:
      - "6379:6379"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "135MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true