services:
  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
      - worker
    ports:
      - "9999:80"
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.08"
          memory: "10MB"

  worker:
    hostname: worker
    image: rodscaldeira/rinha_backend_2025:202507201828
    networks:
      - rinha
      - payment-processor
    environment:
      - ROLE=worker
      - WORKER_POOL_SIZE=4
      - DEFAULT_SERVICE_NAME=default
      - DEFAULT_SERVICE_URL=http://payment-processor-default:8080
      - FALLBACK_SERVICE_NAME=fallback
      - FALLBACK_SERVICE_URL=http://payment-processor-fallback:8080
      - RELEASE_NAME=worker
      - RELEASE_COOKIE=rinha
    deploy:
      resources:
        limits:
          cpus: "0.82"
          memory: "140MB"

  api01: &api
    hostname: api01
    image: rodscaldeira/rinha_backend_2025:202507201828
    ports:
      - "8080:8080"
    networks:
      - rinha
    environment:
      - ROLE=api
      - PORT=8080
      - RELEASE_NAME=api01
      - RELEASE_COOKIE=rinha
    depends_on:
      - worker
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8081:8081"
    environment:
      - ROLE=api
      - PORT=8081
      - RELEASE_NAME=api02
      - RELEASE_COOKIE=rinha

networks:
  rinha:
    name: rinha
    driver: bridge
  payment-processor:
    external: true
