services:
  # -----
  # INFRA
  # -----
  cache:
    image: redis:7.2-alpine
    hostname: cache
    command: redis-server --save "" --appendonly no --maxclients 20000 --maxmemory 40mb --maxmemory-policy allkeys-lru --tcp-keepalive 60
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "45MB"

  # -------------
  # LOAD BALANCER
  # -------------
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40MB"

  # ---
  # API
  # ---
  api1: &api
    image: luzin7/rinha-2025-app:latest
    pull_policy: always
    hostname: api1
    command: node --max-old-space-size=50 --gc-interval=100 dist/app.js
    environment:
      - APP_PORT=9999
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - CACHE_HOST=cache
      - CACHE_PORT=6379
      - NODE_ENV=production
    networks:
      - backend
      - payment-processor
    depends_on:
      cache: { condition: service_healthy }
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "65MB"

  api2:
    <<: *api
    hostname: api2

  # ------
  # WORKER
  # ------
  worker1:
    image: luzin7/rinha-2025-app:latest
    pull_policy: always
    hostname: worker1
    command: node --max-old-space-size=120 --gc-interval=100 dist/bootstrap.js
    environment:
      - APP_PORT=9999
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - CACHE_HOST=cache
      - CACHE_PORT=6379
      - NODE_ENV=production
    networks:
      - backend
      - payment-processor
    depends_on:
      cache: { condition: service_healthy }
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "150MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    name: payment-processor
    external: true
