services:
  redis:
    build:
      context: .
      dockerfile: ./redis/Dockerfile
    hostname: redis
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-socket:/var/run/redis
    command: >
      redis-server
      --save ""
      --appendonly no
      --maxclients 20000
      --hz 1000
    networks:
      - rinha-net
      - payment-processor
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "-s", "/var/run/redis/redis.sock", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "70MB"

  api01: &api
    image: silvaangelolambda/rinha-api-2025:20250731
    command: >
      bun --optimize-for-size /api/index.js
    environment:
      - REDIS_URL=redis://redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    volumes:
      - redis-socket:/var/run/redis
    networks:
      - payment-processor
      - rinha-net
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.525"
          memory: "125MB"

  api02:
    <<: *api

  haproxy:
    image: haproxy:2.9-alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "9999:9999"
    networks:
      - payment-processor
      - rinha-net
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

networks:
  payment-processor:
    external: true
  rinha-net:
    driver: bridge

volumes:
  redis-socket:
