services:
  redis:
    image: redis:8.0.3-alpine
    container_name: backend-fight-go-redis
    restart: unless-stopped
    command:
      [
        "redis-server",
        "--save",
        "",
        "--appendonly",
        "no",
        "--maxclients",
        "10000",
      ]
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "70MB"

  api1: &api1
    image: kauancarvalhocalasans/rinha-go-2025:latest
    container_name: go-api1
    networks:
      - backend
    depends_on:
      - redis
    command: ["api"]
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '60MB'

  api2: &api2
    image: kauancarvalhocalasans/rinha-go-2025:latest
    container_name: go-api2
    networks:
      - backend
    depends_on:
      - redis
    command: ["api"]
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '60MB'

  worker:
    image: kauancarvalhocalasans/rinha-go-2025:latest
    container_name: go-worker
    networks:
      - backend
      - payment-processor
    depends_on:
      - redis
    command: ["worker"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '120MB'

  nginx:
    image: nginx:1.29.0-alpine 
    container_name: backend-fight-go-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    depends_on:
      - api1
      - api2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '40MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
