services:
  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "9999:80"
    depends_on:
      - pod1
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "55MB"
  pod1: &pod
    image: rbenatti8/rinha-backend-2025-api:latest
    container_name: pod1
    pull_policy: always
    networks:
      - backend
      - payment-processor
    environment:
      - REDIS_ADDRESS=redis:6379
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - ACTOR_POOL_SIZE=100
      - WRITE_TIMEOUT=500
      - READ_TIMEOUT=500
      - HEAP_SIZE=15000
      - USE_PREFORK=true
      - IS_PUBLISHER=true
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "65MB"

  pod2:
    <<: *pod
    container_name: pod2
    environment:
      - REDIS_ADDRESS=redis:6379
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - ACTOR_POOL_SIZE=100
      - WRITE_TIMEOUT=500
      - READ_TIMEOUT=500
      - HEAP_SIZE=15000
      - USE_PREFORK=true
      - IS_PUBLISHER=false
  pod3:
    <<: *pod
    container_name: pod3
    environment:
      - REDIS_ADDRESS=redis:6379
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - ACTOR_POOL_SIZE=100
      - WRITE_TIMEOUT=500
      - READ_TIMEOUT=500
      - HEAP_SIZE=15000
      - USE_PREFORK=true
      - IS_PUBLISHER=false
  pod4:
    <<: *pod
    container_name: pod4
    environment:
      - REDIS_ADDRESS=redis:6379
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - ACTOR_POOL_SIZE=100
      - WRITE_TIMEOUT=500
      - READ_TIMEOUT=500
      - HEAP_SIZE=15000
      - USE_PREFORK=true
      - IS_PUBLISHER=false
  redis:
    image: redis:7-alpine
    container_name: redis-cache-rinha
    ports:
      - "6379:6379"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "35MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
