x-template: &template
  image:  joelgarciajr84/rinha-backend-go:rinha-redis-galo4-de-briga
  environment:
    PAYMENT_PROCESSOR_DEFAULT_URL: "http://payment-processor-default:8080"
    PAYMENT_PROCESSOR_FALLBACK_URL: "http://payment-processor-fallback:8080"
    REDIS_URL: "redis:6379"
    PORT: 80
  networks:
    - backend
    - payment-processor
  deploy:
    resources:
      limits:
        cpus: "0.5"
        memory: "115MB"

services:
  galo01:
    <<: *template
    hostname: galo01
    depends_on:
      - redis
  galo02:
    <<: *template
    hostname: galo02
    depends_on:
      - redis
  
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:80"
    depends_on:
      - galo01
      - galo02
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "70MB"
  redis:
    image: redis:8.0.3-alpine
    hostname: redis
    networks:
      - backend
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec"]
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
