version: '3.8'

services:
  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx_load_balancer
    ports:
      - "9999:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rinha-api-1
      - rinha-api-2
      - rinha-api-3
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "15MB"

  rinha-api-1:
    image: jhamiltonjunior/rinha-go-mongo-only-default:0.0.3
    container_name: rinha-api-1
    environment:
      - RUN_VERIFY_PAYMENT_SERVICE=true
      - APP_PORT=3000
      - REDIS_ADDR=redis:6379
      - POSTGRES_URL=postgres://user:password-very-har@postgres:5432/rinha_de_backend?sslmode=disable
      - NATS_URL=nats://nats:4222
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      - mongodb
    networks:
      - app-network
      - payment-processor
    volumes:
      - ./:/app
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "30MB"

  rinha-api-2:
    image: jhamiltonjunior/rinha-go-mongo-only-default:0.0.3
    container_name: rinha-api-2
    environment:
      - APP_PORT=3000
      - REDIS_ADDR=redis:6379
      - POSTGRES_URL=postgres://user:password-very-har@postgres:5432/rinha_de_backend?sslmode=disable
      - NATS_URL=nats://nats:4222
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      - mongodb
    networks:
      - app-network
      - payment-processor
    volumes:
      - ./:/app
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "30MB"

  rinha-api-3:
    image: jhamiltonjunior/rinha-go-mongo-only-default:0.0.3
    container_name: rinha-api-3
    environment:
      - APP_PORT=3000
      - REDIS_ADDR=redis:6379
      - POSTGRES_URL=postgres://user:password-very-har@postgres:5432/rinha_de_backend?sslmode=disable
      - NATS_URL=nats://nats:4222
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      - mongodb
    networks:
      - app-network
      - payment-processor
    volumes:
      - ./:/app
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "30MB"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: very_hard_password
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "245MB"

networks:
  app-network:
    driver: bridge
  payment-processor:
    external: true

volumes:
  mongo_data:
