x-common-api-env: &common-env
  NATS_URL: nats://nats:4222
  REDIS_HOST: redis:6379
  PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
  PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
  NATS_MAX_ACK_PENDING: 30
  NATS_MAX_DELIVER: 3
  REDIS_POOL_SIZE: 20

x-service-templates:
  api: &api
    image: ghcr.io/lczago/rinha-25-go:v1.1.0
    networks:
      - rinha
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '120MB'
    depends_on:
      nats:
        condition: service_healthy
      redis:
        condition: service_healthy

services:
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    networks:
      - rinha
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '20MB'

  api01:
    <<: *api
    container_name: api01
    environment:
      <<: *common-env
      SERVER_PORT: 8081

  api02:
    <<: *api
    container_name: api02
    environment:
      <<: *common-env
      SERVER_PORT: 8082

  nats:
    image: nats:2.11.6-alpine3.22
    hostname: nats
    networks:
      - rinha
    environment:
      - NATS_ENABLE_AUTH=false
    command:
      - "--jetstream"
      - "-m"
      - "8222"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '40MB'
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8222/healthz" ]
      interval: 2s
      timeout: 2s
      retries: 5

  redis:
    image: redis:8.0.3-alpine
    hostname: redis
    networks:
      - rinha
    command: [ "redis-server", "--save", "", "--appendonly", "no", "--io-threads", "4" ]
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 2s
      timeout: 2s
      retries: 5

networks:
  payment-processor:
    external: true
  rinha:
    driver: bridge