version: "3.9"

services:
  redis:
    image: redis:7
    container_name: rinha-redis
    ports:
      - "6379:6379"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 80MB

  backend1:
    image: adryan1928/rinha-backend:latest
    container_name: backend-1
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
      PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
    ports:
      - "8003:8000"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 80MB

  backend2:
    image: adryan1928/rinha-backend:latest
    container_name: backend-2
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
      PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
    ports:
      - "8004:8000"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 80MB

  nginx:
    image: nginx:stable
    container_name: nginx-loadbalancer
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 90MB

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
