services:
  redis:
    image: redis:8.0.3-alpine
    ports:
      - "6379:6379"
    command: >
      redis-server
      --maxmemory 100mb
      --save ""
      --appendonly no
      --tcp-keepalive 60
      --hz 20
      --maxclients 1000
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus:  "0.3"
          memory: "45MB"
    networks:
      - backend-rinha
  api1: &api
    image: caiqueborges/rinha-backend-2025:1.0.0
    hostname: api1
    environment:
      - BACKEND_MODE=api
      - REDIS_HOST=redis://redis:6379
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "95MB"
    networks:
      - backend-rinha
      - payment-processor
  api2:
    <<: *api
    hostname: api2
  worker1:
    <<: *api
    hostname: worker1
    environment:
      - BACKEND_MODE=worker
      - PAYMENT_WORKERS_SIZE=10
      - REDIS_HOST=redis://redis:6379
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"
  nginx:
    image: nginx:1.27.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - payment-processor
      - backend-rinha
    depends_on:
      - api1
      - api2
      - worker1
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "15MB"
networks:
  backend-rinha:
    driver: bridge
  payment-processor:
    external: true