services:
  nginx:
    image: nginx:alpine
    container_name: rinha-nginx-node
    restart: unless-stopped
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-api-1
      - backend-api-2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "48MB"

  backend-api-1: &api
    image: ricassiocosta/rinha-backend-2025-node:v0.1.6
    container_name: rinha-api-node-1
    restart: unless-stopped
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - MAX_PARALLELISM=6
    depends_on:
      - redis
    volumes:
      - redis-socket:/var/run/redis
    networks:
      - backend
      - payment-processor
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "108MB"

  backend-api-2:
    <<: *api
    container_name: rinha-api-node-2

  redis:
    image: redis:7-alpine
    container_name: rinha-redis-node
    restart: unless-stopped
    command: [
        "sh",
        "-c",
        "mkdir -p /var/run/redis && \
        redis-server \
        --save '' \
        --appendonly no \
        --maxclients 5000 \
        --unixsocket /var/run/redis/redis.sock \
        --unixsocketperm 777 \
        --port 0 \
        --protected-mode no \
        --hz 10",
      ]
    networks:
      - backend
    volumes:
      - redis-socket:/var/run/redis
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "86MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  redis-socket:
