services:
  nginx:
    image: nginx:latest
    container_name: rinha-nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api01
      - api02
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "40mb"
  api01:
    image: fabriciopalmeiradev/rinha-de-backend-2025-quarkus
    container_name: api01
    networks:
      - backend
      - payment-processor
    environment:
      DB_USERNAME: rinha
      DB_PASSWORD: rinha123
      DB_HOST: jdbc:postgresql://postgres:5432/rinha
      DEFAULT_URL: http://payment-processor-default:8080
      FALLBACK_URL: http://payment-processor-fallback:8080
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "120MB"
  api02:
    image: fabriciopalmeiradev/rinha-de-backend-2025-quarkus
    container_name: api02
    networks:
      - backend
      - payment-processor
    environment:
      DB_USERNAME: rinha
      DB_PASSWORD: rinha123
      DB_HOST: jdbc:postgresql://postgres:5432/rinha
      DEFAULT_URL: http://payment-processor-default:8080
      FALLBACK_URL: http://payment-processor-fallback:8080
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "120MB"
  postgres:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    networks:
      - backend
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha123
      POSTGRES_DB: rinha
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "70MB"


networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
