x-enviromments: &x-enviromments
  - AMQP_URL: "amqp://guest:guest@lavinmq:5672/"
  - PREFETCH_COUNT: "0"
  - SHARD_COUNT: "1"
  - PROCESSOR_URL: "http://payment-processor-default:8080"
  - FALLBACK_URL: "http://payment-processor-fallback:8080"
  - DISABLE_LOG: "true"

version: '3.4'
services:
  app1: &app
    image: docker.io/lukas8219/rinha-de-backend-2025-app:main-1ca9312f1-1753450997
    user: "1001:1001"
    hostname: app1
    restart: unless-stopped
    environment:
      <<: *x-enviromments
      SOCKET_PATH: "/shared/sockets/app1.sock"
    volumes:
      - unix_sockets:/shared/sockets
    networks:
      - backend
      - payment-processor
    expose:
      - "3000"
    depends_on:
      lavinmq:
        condition: service_healthy
      consumer:
        condition: service_started
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: '50MB'
  app2:
    <<: *app
    user: "1001:1001"
    environment:
      <<: *x-enviromments
      SOCKET_PATH: "/shared/sockets/app2.sock"
    volumes:
      - unix_sockets:/shared/sockets
    hostname: app2
    depends_on:
      lavinmq:
        condition: service_healthy
      consumer:
        condition: service_started

  consumer: &consumer
    <<: *app
    user: "1001:1001"
    hostname: "1"
    environment:
      <<: *x-enviromments
      SOCKET_PATH: "/shared/sockets/1.sock"
    volumes:
      - unix_sockets:/shared/sockets
    cpu_shares: 3072
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '140MB'
        reservations:
          cpus: '0.9'
          memory: '140MB'
    image: docker.io/lukas8219/rinha-de-backend-2025-app:main-1ca9312f1-1753450997
    depends_on:
      lavinmq:
        condition: service_healthy

  lavinmq:
    image: cloudamqp/lavinmq:latest
    container_name: lavinmq
    healthcheck:
      test: ["CMD", "lavinmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 5s
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '35MB'
        reservations:
          cpus: '0.1'
          memory: '35MB'

  nginx: # Load Balancer
    image: nginx:latest
    user: "1001:1001"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - unix_sockets:/shared/sockets
      - nginx_cache:/var/cache/nginx
      - nginx_run:/var/run
      - nginx_log:/var/log/nginx
    depends_on:
      - app1
      - app2
      - lavinmq
      - consumer
    ports:
      - "9999:9999"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    networks:
      - backend
    cpu_shares: 2048
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '35MB'
        reservations:
          cpus: '0.1'
          memory: '35MB'

  socket-stats:
    image: alpine:latest
    depends_on:
      - nginx
    volumes:
      - unix_sockets:/shared/sockets
    entrypoint: ["/bin/sh", "-c"]
    restart: no
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '6MB'
        reservations:
          cpus: '0.1'
          memory: '6MB'
    command:
      - |
        # Wait for nginx to be up by checking the port
        echo "nginx is up, statting unix socket files:"
        stat /shared/sockets/* || echo "No socket files found"


volumes:
  unix_sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "uid=1001,gid=1001,mode=0777"
  nginx_cache:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "uid=1001,gid=1001,mode=0755"
  nginx_run:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "uid=1001,gid=1001,mode=0755"
  nginx_log:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "uid=1001,gid=1001,mode=0755"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

