services:
  api-1: &api-service
    image: eber404/dudebank:0.0.8
    env_file:
      - .env
    environment:
      - SERVER_SOCKET_PATH=/tmp/api_1.sock
    networks:
      - backend
      - payment-processor
    volumes:
      - socket_data:/tmp
    depends_on:
      - database
    deploy:
      resources:
        limits:
          cpus: '0.675'
          memory: '135MB'

  api-2:
    <<: *api-service
    environment:
      - SERVER_SOCKET_PATH=/tmp/api_2.sock

  database:
    image: eber404/dudebank-db:0.0.8
    env_file:
      - .env
    volumes:
      - socket_data:/tmp
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '50MB'

  balancer:
    container_name: balancer
    image: openresty/openresty:bullseye
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - socket_data:/tmp
    depends_on:
      - api-1
      - api-2
    networks:
      - backend
    ports:
      - '9999:80'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '30MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  socket_data:
