services:
  haproxy:
    image: haproxy:3.1.8-alpine3.22
    container_name: eliot-haproxy
    hostname: eliot-haproxy
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - eliot1
      - eliot2
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "40MB"
    networks:
      - payment-processor
      - rinha

  eliot1:
    image: fabianoflorentino/eliot:v0.0.2
    container_name: eliot-1
    hostname: eliot-1
    environment:
      HTTP_ADDR: ":8080"
      REDIS_ADDR: "redis:6379"
      REDIS_POOL: "250"
      PROCESSOR_DEFAULT_URL: "http://payment-processor-default:8080"
      PROCESSOR_FALLBACK_URL: "http://payment-processor-fallback:8080"
      TIMEOUT_MS: "120"
      HEDGE_MS: "40"
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "120MB"
    networks:
      - payment-processor
      - rinha

  eliot2:
    image: fabianoflorentino/eliot:v0.0.2
    container_name: eliot-2
    hostname: eliot-2
    environment:
      HTTP_ADDR: ":8080"
      REDIS_ADDR: "redis:6379"
      REDIS_POOL: "250"
      PROCESSOR_DEFAULT_URL: "http://payment-processor-default:8080"
      PROCESSOR_FALLBACK_URL: "http://payment-processor-fallback:8080"
      TIMEOUT_MS: "120"
      HEDGE_MS: "40"
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "120MB"
    networks:
      - payment-processor
      - rinha

  redis:
    image: redis:alpine3.22
    container_name: eliot-redis
    hostname: eliot-redis
    command: ["redis-server", "--save", "", "--appendonly", "no", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "70MB"
    networks:
      - rinha

networks:
  rinha:
  payment-processor:
    external: true
    name: payment-processor
