x-api_template: &api
  image: ghcr.io/lothyriel/rinha_2025:v0.4.1
  volumes:
    - uds:/var/run
  command: ["-m", "api"]
  depends_on:
    - worker
  environment:
    RUST_LOG: "info"
  deploy:
    resources:
      limits:
        cpus: "0.4"
        memory: "80MB"

services:
  lb:
    container_name: balancer
    image: openresty/openresty:bullseye
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - uds:/var/run
    depends_on:
      - api0
      - api1
    ports:
      - "9999:80"
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "80MB"

  api0:
    <<: *api
    environment:
      API_N: "0"
      RUST_LOG: "info"
      WORKER_SOCKET: "/var/run/worker.socket"

  api1:
    <<: *api
    environment:
      API_N: "1"
      RUST_LOG: "info"
      WORKER_SOCKET: "/var/run/worker.socket"

  worker:
    image: ghcr.io/lothyriel/rinha_2025:v0.4.1
    command: ["-m", "worker"]
    networks:
      - payment-processor
    volumes:
      - uds:/var/run
    environment:
      WORKER_SOCKET: "/var/run/worker.socket"
      RUST_LOG: "info"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "110MB"

volumes:
  uds:

networks:
  payment-processor:
    external: true
