services:
  api_0: &api
    image: ghcr.io/lothyriel/rinha_2025:v0.1.0
    networks:
      - backend
    volumes:
      - data:/data
    command: ["-m", "api", "-w", "worker:80"]
    depends_on:
      - worker
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "80MB"

  api_1:
    <<: *api

  worker:
    image: ghcr.io/lothyriel/rinha_2025:v0.1.0
    networks:
      - backend
      - payment-processor
    volumes:
      - data:/data
    command: ["-m", "worker"]
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "140MB"

  nginx:
    image: nginx:latest
    ports:
      - "9999:80"
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_0
      - api_1
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

volumes:
  data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
