x-api_template: &api
  image: ghcr.io/lothyriel/rinha_2025:v0.1.7
  volumes:
    - uds:/var/run
  command: ["-m", "api"]
  depends_on:
    - worker
  deploy:
    resources:
      limits:
        cpus: "0.35"
        memory: "60MB"

services:
  api_0:
    <<: *api
    environment:
      NGINX_SOCKET: "/var/run/api_0.sock"
      RUST_LOG: "info"

  api_1:
    <<: *api
    environment:
      NGINX_SOCKET: "/var/run/api_1.sock"
      RUST_LOG: "info"

  worker:
    image: ghcr.io/lothyriel/rinha_2025:v0.1.7
    networks:
      - payment-processor
    volumes:
      - uds:/var/run
    command: ["-m", "worker"]
    environment:
      RUST_LOG: "info"
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "150MB"

  nginx:
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - uds:/var/run
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_0
      - api_1
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "80MB"

volumes:
  uds:

networks:
  payment-processor:
    external: true
