services:
  nginx:
    image: nginx:1.29.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - backend
    ports:
      - "9999:80"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  app1: &api
    image: viweesleyy/rinha-2025:0.1
    ports:
      - "9501:9501"
    networks:
      - backend
      - payment-processor
    command: php /opt/www/bin/hyperf.php start
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

  app2:
    <<: *api
    ports:
      - "9502:9501"
    command: php /opt/www/bin/hyperf.php start

  worker:
    <<: *api
    command: php /opt/www/bin/hyperf.php payment:queue
    ports: []
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "60MB"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "40MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true