x-service-templates:
  payment-gateway: &payment-gateway
    image: phaalonso/rinha-backend-2025-java:0.0.1
    hostname: api01
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "1.4"
          memory: "340MB"

services:
  api01:
    <<: *payment-gateway
    container_name: api01
    hostname: api01
    ports:
      - "8080:8080"

  #  api02:
  #    <<: *payment-gateway
  #    container_name: api02
  #    hostname: api02
  #    ports:
  #      - "8081:8080"

  nginx:
    image: nginx:alpine
    container_name: rinha-router-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
