services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 40MB

  app-native-1:
    image: docker.io/maxsonferovante/api-payment-processor:latest
    pull_policy: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TIMEOUT: 5000ms
      REDIS_QUEUE_PAYMENTS_MAIN: rinha-payments-main-queue      
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 60MB

  app-native-2:
    image: docker.io/maxsonferovante/api-payment-processor:latest
    pull_policy: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TIMEOUT: 5000ms
      REDIS_QUEUE_PAYMENTS_MAIN: rinha-payments-main-queue      
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 60MB

  # Processador ass√≠ncrono de pagamentos - consome mensagens do Redis
  async-worker:
    image: docker.io/maxsonferovante/async-payment-processor:latest
    pull_policy: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TIMEOUT: 5000ms
      REDIS_QUEUE_PAYMENTS_MAIN: rinha-payments-main-queue
      PAYMENT_PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
      WORKER_MAX_CONCURRENT_PAYMENTS: 70
      WORKER_BATCH_SIZE: 75
      WORKER_EXECUTION_DELAY: 200
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 60MB
  async-worker-2:
      image: docker.io/maxsonferovante/async-payment-processor:latest
      pull_policy: always
      environment:
        REDIS_HOST: redis
        REDIS_PORT: 6379
        REDIS_TIMEOUT: 5000ms
        REDIS_QUEUE_PAYMENTS_MAIN: rinha-payments-main-queue
        PAYMENT_PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
        PAYMENT_PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
        WORKER_MAX_CONCURRENT_PAYMENTS: 70
        WORKER_BATCH_SIZE: 75
        WORKER_EXECUTION_DELAY: 200
      depends_on:
        redis:
          condition: service_healthy
      networks:
        - backend
        - payment-processor
      deploy:
        resources:
          limits:
            cpus: '0.2'
            memory: 60MB

  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-native-1
      - app-native-2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 70MB

networks:
  backend:
    driver: bridge
    name: backend
  payment-processor:
    external: true
