services:
  backend-1:
    image: gabxdevv/rinha-backend-2025-java-gabxdev-oli:1.0.3
    restart: always
    environment:
      RETRY_API_DEFAULT: 15
      WORKER_POOL_SIZE: 16
      URL_PROCESSOR_DEFAULT: http://payment-processor-default:8080/payments
      URL_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080/payments
      BACK_END_URL: http://backend-2:8080
      UDP_CHANNEL_PORT: 9001
      UDP_CHANNEL_INTERNAL_PORT: 9003
      EXTERNAL_UDP_HOST: backend-2
      EXTERNAL_UDP_PORT: 9004
      HANDLER_UDP_POOL_SIZE: 6
      LB_URL: load-balancer
      JAVA_OPTS: >-
        -server
        -XX:+UseG1GC
        -XX:+UseFastAccessorMethods
        -Xlog:disable
        -XX:-PrintGC
        -XX:+UseStringCache
        -XX:-PrintGCDetails
        -XX:-FlightRecorder
        -XX:+DisableExplicitGC
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '125MB'

  backend-2:
    image: gabxdevv/rinha-backend-2025-java-gabxdev-oli:1.0.3
    restart: always
    environment:
      RETRY_API_DEFAULT: 15
      WORKER_POOL_SIZE: 16
      URL_PROCESSOR_DEFAULT: http://payment-processor-default:8080/payments
      URL_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080/payments
      BACK_END_URL: http://backend-1:8080
      UDP_CHANNEL_PORT: 9002
      UDP_CHANNEL_INTERNAL_PORT: 9004
      EXTERNAL_UDP_HOST: backend-1
      EXTERNAL_UDP_PORT: 9003
      HANDLER_UDP_POOL_SIZE: 6
      LB_URL: load-balancer
      JAVA_OPTS: >-
        -server
        -XX:+UseG1GC
        -XX:+UseFastAccessorMethods
        -Xlog:disable
        -XX:-PrintGC
        -XX:+UseStringCache
        -XX:-PrintGCDetails
        -XX:-FlightRecorder
        -XX:+DisableExplicitGC
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '125MB'

  load-balancer:
    image: gabxdevv/loud-balance-java-gabxv-plus:1.0.1-sync
    restart: always
    depends_on:
      - backend-1
      - backend-2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "100MB"
    environment:
      BACK_END_1_URL: backend-1
      BACK_END_2_URL: backend-2
      JAVA_OPTS: >-
        -server
        -XX:+UseG1GC
        -XX:+UseFastAccessorMethods
        -Xlog:disable
        -XX:-PrintGC
        -XX:+UseStringCache
        -XX:-PrintGCDetails
        -XX:-FlightRecorder
        -XX:+DisableExplicitGC

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true