services:
  
  api01: 
    image: ghcr.io/rst77/devpr2025/cli-app:5
    hostname: api01
    environment:
          LB_URL: lb-server
          PAYMENT_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080
          PAYMENT_PROCESSOR_DEFAULT: http://payment-processor-default:8080    
    networks:
      - payment-processor
      - rinha-net
    depends_on:
      - lb      
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "125MB"

  api02: 
    image: ghcr.io/rst77/devpr2025/cli-app:5
    hostname: api02
    environment:
          LB_URL: lb-server
          PAYMENT_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080
          PAYMENT_PROCESSOR_DEFAULT: http://payment-processor-default:8080    
    networks:
      - payment-processor
      - rinha-net
    depends_on:
      - lb      
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "125MB"

  lb:
    hostname: lb-server
    image: ghcr.io/rst77/devpr2025/api-app:5
    environment:
          PAYMENT_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080
          PAYMENT_PROCESSOR_DEFAULT: http://payment-processor-default:8080    
    ports:
      - "9999:9999"
      - "5000:5000"
    networks:
      - payment-processor
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

networks:
  payment-processor:
    external: true
  rinha-net:
    driver: bridge